# Generated by Django 6.0.6 on 2026-07-12 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('overall_score', models.FloatField(default=0)),
                ('total_issues', models.IntegerField(default=0)),
                ('total_security_issues', models.IntegerField(default=0)),
                ('project_summary', models.TextField(blank=True)),
                ('top_improvements', models.JSONField(default=list)),
                ('code_smells', models.JSONField(default=list)),
                ('technical_debt', models.JSONField(default=list)),
                ('overall_suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Analyzed', 'Analyzed')], default='Pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('relative_path', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('language', models.CharField(default='Python', max_length=20)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='analyzer.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pylint_score', models.FloatField(max_length=10)),
                ('pylint_report', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('issue_count', models.IntegerField(default=0)),
                ('quality_status', models.CharField(default='Unknown', max_length=30)),
                ('recommendations', models.TextField(blank=True)),
                ('pylint_json', models.TextField(blank=True)),
                ('security_level', models.CharField(default='Safe', max_length=10)),
                ('security_issue_count', models.IntegerField(default=0)),
                ('security_report', models.TextField(blank=True)),
                ('ai_score', models.FloatField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_strengths', models.JSONField(default=list)),
                ('ai_weaknesses', models.JSONField(default=list)),
                ('ai_suggestions', models.JSONField(default=list)),
                ('ai_changes', models.JSONField(default=list)),
                ('ai_fixed_code', models.TextField(blank=True)),
                ('ai_fix_explanation', models.TextField(blank=True)),
                ('maintainability_score', models.FloatField(default=0)),
                ('readability_score', models.FloatField(default=0)),
                ('ai_security', models.CharField(blank=True, max_length=30)),
                ('ai_confidence', models.FloatField(default=0)),
                ('analysis_duration', models.FloatField(default=0)),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyzer.uploadedfile')),
            ],
        ),
    ]
