# Generated by Django 6.0.6 on 2026-06-24 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pylint_score', models.CharField(max_length=10)),
                ('pylint_report', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyzer.uploadedfile')),
            ],
        ),
    ]
