# Generated by Django 6.0.6 on 2026-07-14 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='total_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='recommendations',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='uploaded_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analyzer.uploadedfile'),
        ),
    ]
