# Generated by Django 6.0.6 on 2026-06-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysisreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='issue_count',
            field=models.IntegerField(default=0),
        ),
    ]
