# Generated by Django 6.0.6 on 2026-06-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_analysisreport_issue_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='quality_status',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
    ]
