# Generated by Django 6.0.6 on 2026-06-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_analysisreport_quality_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='security_issue_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='security_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='security_score',
            field=models.IntegerField(default=100),
        ),
    ]
