# Generated by Django 6.0.6 on 2026-06-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_analysisreport_security_issue_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='pylint_json',
            field=models.TextField(blank=True),
        ),
    ]
