# Generated by Django 6.0.6 on 2026-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_analysisreport_pylint_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='pylint_score',
            field=models.FloatField(max_length=10),
        ),
    ]
